# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 663d261ebe0c011659d2066cbe77465731965790d307ec9d25a9d7d5756358b69c690e5fe019a1d372e0c519604f15a3f0380b580136f54ed2cff3ec52b1158e

test:
  secret_key_base: d992b29c96a59b0dbc9d85470fd1e6856db1a403c330f5ed13989d4c7a09a1e050a95c39506bab652784670b464bb52ecfa2e0fa11a3443084b7143ff0859fcc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
